-- Painel de Tickets: tabelas no Postgres (Supabase).
-- Rode no SQL Editor do Supabase (ou via scripts/aplicar-migracoes.js).
--
-- Decisões que preservam o comportamento da planilha:
--  * row_index = "número da linha" da planilha. É o id que a tela, os links
--    (/tickets#/t/<n>) e as notificações já usam; tickets novos continuam a
--    sequência. NÃO é reaproveitado (identity), mesmo se um ticket sumir.
--  * Datas são "timestamp" SEM fuso, guardando a hora de Brasília exatamente
--    como o Apps Script devolvia ("yyyy-MM-ddTHH:mm:ss"). Os painéis que
--    leem tickets já assumem isso; guardar com fuso mudaria o dia de alguns
--    tickets perto da meia-noite.
--  * Textos nunca ficam NULL (vazio = ''), igual à planilha.

create table if not exists tickets (
  row_index        bigint generated by default as identity (start with 2) primary key,  -- planilha: linha 1 = cabeçalho
  id_ticket        text        not null,
  pedido           text        not null default '',
  id_venda         text        not null default '',
  identificador    text        not null default '',
  fabrica          text        not null default '',
  setor            text        not null default '',
  responsavel      text        not null default '',
  responsavel_slug text        not null default '',
  status           text        not null default 'Aberto',
  data_abertura    timestamp,
  data_fechamento  timestamp,
  origem           text        not null default '',
  link             text        not null default '',
  observacao       text        not null default '',
  anexos           text        not null default '',   -- URLs do Drive separadas por vírgula (como na planilha)
  tem_evento       boolean     not null default false,
  data_evento      timestamp,
  entrega          text        not null default '',
  aeroporto        text        not null default '',
  ppe                              timestamp,
  previsao_finalizacao             timestamp,
  p_folha                          timestamp,
  novo_prazo                       timestamp,
  atraso_notificado boolean    not null default false,
  negocio_id       text        not null default '',
  codigo_rastreio  text        not null default '',
  previsao_entrega_transportadora  timestamp
);

-- id_ticket é só o rótulo mostrado ("T00123"); o identificador de verdade é row_index.
-- NÃO é único: a planilha antiga já tinha ids repetidos entre tickets diferentes
-- e a migração mantém tudo como estava. Ids novos nunca colidem com os existentes.
create index if not exists tickets_id_ticket_idx on tickets (id_ticket);
create index if not exists tickets_status_idx on tickets (status);
create index if not exists tickets_responsavel_idx on tickets (responsavel_slug);
create index if not exists tickets_fechamento_idx on tickets (data_fechamento);
create index if not exists tickets_negocio_idx on tickets (negocio_id) where negocio_id <> '';

create table if not exists ticket_historico (
  id               bigint generated always as identity primary key,
  ticket_row_index bigint      not null,
  id_ticket        text        not null default '',
  quando           timestamp   not null default (now() at time zone 'America/Sao_Paulo'),
  usuario          text        not null default '—',
  acao             text        not null default '',
  detalhe          text        not null default '',
  slug             text        not null default ''
);
create index if not exists ticket_historico_ticket_idx on ticket_historico (ticket_row_index, id);
