-- Painel de Erros: casos e histórico.
--
--  * row_index = "número da linha" da planilha "Cadastro de erros". É o id que a
--    tela, os links (/erros#/casos/<n>, /erros?refab=<n>) e as notificações já
--    usam; casos novos continuam a sequência.
--  * Textos nunca ficam NULL (vazio = ''), como na planilha. qtd e custo ficam
--    NULL quando não informados (a planilha devolvia '').
--  * data = dia do registro (a planilha guardava dd/MM/aaaa).
--  * registrado_por_slug = quem registrou o caso (antes: lido do Histórico, evento
--    "Caso registrado"); guardado direto no caso para a fila de Refabricação.

create table if not exists erros_casos (
  row_index           bigint generated by default as identity (start with 2) primary key,
  data                date,
  auditoria           boolean not null default false,
  id_venda            text    not null default '',
  nome_card           text    not null default '',
  descricao           text    not null default '',
  link_pedido         text    not null default '',  -- vazio = usa o primeiro link da descrição (casos antigos)
  quem_cadastrou      text    not null default '',
  culpa_de            text    not null default '',
  setor               text    not null default '',
  responsavel         text    not null default '',
  empresa             text    not null default '',
  tipo_problema       text    not null default '',
  subproblema         text    not null default '',
  qtd                 numeric,
  custo               numeric,
  tipo_produto        text    not null default '',
  linha               text    not null default '',
  que_fim             text    not null default '',
  tipo_resolucao      text    not null default '',
  status              text    not null default '',
  foto                text    not null default '',  -- URLs do Drive separadas por vírgula (como na planilha)
  aprovacao_refab     text    not null default '',  -- '', Pendente, Aprovado, Reprovado, Finalizado
  comentario_aprovacao text   not null default '',
  comentario_final    text    not null default '',
  registrado_por_slug text    not null default ''
);
create index if not exists erros_casos_status_idx on erros_casos (status);
create index if not exists erros_casos_data_idx on erros_casos (data);
create index if not exists erros_casos_refab_idx on erros_casos (aprovacao_refab) where aprovacao_refab <> '';

create table if not exists erros_historico (
  id             bigint generated always as identity primary key,
  caso_row_index bigint    not null,
  id_venda       text      not null default '',
  quando         timestamp not null default (now() at time zone 'America/Sao_Paulo'),  -- hora de Brasília
  usuario        text      not null default '—',
  acao           text      not null default '',
  detalhe        text      not null default '',
  slug           text      not null default ''
);
create index if not exists erros_historico_caso_idx on erros_historico (caso_row_index, id);
