-- Usuários do hub, Quitações Pendentes, Auditoria de Qualidade e Foco/Agenda da Semana.
-- Mesmo contrato de dados que as planilhas devolviam (ver src/services/*Db.service.js).
--
--  * Datas "com hora" são timestamptz (instante real). Datas "sem hora" são date.
--  * RLS ligado em tudo: o hub conecta como dono (ignora RLS); a API pública do Supabase não enxerga nada.

-- ── Usuários (aba HubUsuarios do Painel SAC) ──────────────────────────────
create table if not exists hub_usuarios (
  ordem                 bigint generated always as identity primary key,
  id                    text    not null,
  usuario               text    not null,
  senha_hash            text    not null,
  nome                  text    not null default '',
  slug                  text    not null,
  role                  text    not null default 'colaborador',
  tipo                  text,
  paineis               text[]  not null default '{}',
  indicadores_pendentes boolean not null default false
);
create unique index if not exists hub_usuarios_usuario_uq on hub_usuarios (lower(btrim(usuario)));
create index if not exists hub_usuarios_slug_idx on hub_usuarios (slug);

-- ── Quitações Pendentes (aba Quitacoes) ───────────────────────────────────
create table if not exists quitacoes (
  ordem               bigint generated always as identity primary key,
  id                  text        not null unique,
  data_cadastro       timestamptz not null default now(),
  id_venda_omie       text        not null default '',
  cliente             text        not null default '',
  data_prevista       date,
  link_crm            text        not null default '',
  modalidade          text        not null default '',
  tipo_envio_aereo    text        not null default '',
  aeroporto           text        not null default '',
  frete_dedicado      boolean     not null default false,
  transportadora      text        not null default '',
  entregador          text        not null default '',
  observacao          text        not null default '',
  cadastrado_por_slug text        not null default '',
  cadastrado_por_nome text        not null default '',
  status              text        not null default 'pendente',
  data_pagamento      timestamptz
);
create index if not exists quitacoes_status_idx on quitacoes (status, data_cadastro desc);

-- ── Auditoria de Qualidade (aba Sistema_Registro) ─────────────────────────
create table if not exists auditorias (
  ordem           bigint generated always as identity primary key,
  registrado_em   timestamptz not null default now(),
  data            date        not null,
  semana          text        not null default '',
  auditado_por    text        not null default '',
  agente          text        not null default '',
  tipo_ocorrencia text        not null default '',
  canal           text        not null default '',
  conversation_id text        not null default '',
  c11 numeric not null default 0, c12 numeric not null default 0, c13 numeric not null default 0, c14 numeric not null default 0,
  c21 numeric not null default 0, c22 numeric not null default 0, c23 numeric not null default 0, c24 numeric not null default 0,
  c31 numeric not null default 0, c32 numeric not null default 0, c33 numeric not null default 0, c34 numeric not null default 0,
  s1 numeric not null default 0, s2 numeric not null default 0, s3 numeric not null default 0, total numeric not null default 0,
  classificacao   text        not null default '',
  fg1 boolean not null default false, fg2 boolean not null default false, fg3 boolean not null default false, fg4 boolean not null default false,
  falha_grave     boolean     not null default false,
  observacoes     text        not null default ''
);
create index if not exists auditorias_data_idx on auditorias (data);
create index if not exists auditorias_conversa_idx on auditorias (conversation_id);

-- ── Foco da Semana + Agenda da Semana (aba "AGENDA E FOCO") ───────────────
-- agenda_eventos.id é o número da linha da planilha (o hub usa como "linha" para editar/excluir);
-- os novos continuam a partir da linha 5 em diante, sem reaproveitar.
create table if not exists agenda_foco (
  id    smallint primary key check (id = 1),
  texto text not null default ''
);
create table if not exists agenda_eventos (
  id        bigint generated by default as identity (start with 5) primary key,
  dia       text not null default '',
  hora      text not null default '',
  descricao text not null default '',
  tipo      text not null default 'Outro'
);

alter table hub_usuarios    enable row level security;
alter table quitacoes       enable row level security;
alter table auditorias      enable row level security;
alter table agenda_foco     enable row level security;
alter table agenda_eventos  enable row level security;
