-- Painel de Produção SBP (Wallac) em Postgres. Os cards de COMPRA continuam vindo da aba LTV (planilha manual de outra
-- pessoa, só leitura); o resto passa para o banco:
--   wallac_status           andamento de cada card de compra (a chave é o número da linha na LTV, "ltv-<linha>")
--   wallac_estoque          produtos e quantidades disponíveis
--   wallac_solicitacoes     pedidos de personalização feitos pelo formulário público (cards "est-<id>")
--   wallac_premiacao        fechamento semanal da premiação (SB Coin)
-- wallac_estoque.id e wallac_solicitacoes.id continuam a numeração de linhas da planilha (começam em 2).
create table if not exists wallac_status (
  linha_ltv            integer     primary key,
  status_atual         text        not null default 'A chegar',
  data_recebido        timestamptz,
  data_inicio_producao timestamptz,
  data_finalizado      timestamptz
);

create table if not exists wallac_estoque (
  id         bigint generated by default as identity (start with 2) primary key,
  produto    text    not null,
  quantidade numeric not null default 0
);
create index if not exists wallac_estoque_produto_idx on wallac_estoque (upper(btrim(produto)));

create table if not exists wallac_solicitacoes (
  id                   bigint generated by default as identity (start with 2) primary key,
  produto              text        not null default '',
  quantidade           numeric     not null default 0,
  id_venda_cliente     text        not null default '',
  prazo_producao       text,                 -- "AAAA-MM-DD" (como o formulário envia)
  prazo_entrega        text,
  observacoes          text        not null default '',
  logo_url             text        not null default '',
  status_atual         text        not null default 'Recebido',
  data_recebido        timestamptz,
  data_inicio_producao timestamptz,
  data_finalizado      timestamptz,
  solicitante          text        not null default ''
);
create index if not exists wallac_solicitacoes_status_idx on wallac_solicitacoes (status_atual, data_finalizado);

create table if not exists wallac_premiacao (
  semana_inicio           date primary key,
  semana_fim              date    not null,
  pecas_no_prazo          integer not null default 0,
  faixa                   text    not null default 'Nenhuma',
  coins_da_semana         integer not null default 0,
  mes_referencia          text    not null default '',   -- "AAAA-MM" do mês da sexta-feira
  coins_acumulados_no_mes integer not null default 0
);

alter table wallac_status       enable row level security;
alter table wallac_estoque      enable row level security;
alter table wallac_solicitacoes enable row level security;
alter table wallac_premiacao    enable row level security;
