// Portado de azul-rastreio-crm (ESM compilado) para CommonJS; lógica idêntica. Rastreio Azul Logística (Integração Fácil).
const CODIGOS_AZUL = {
    "1": { descricao: "ENTREGA REALIZADA NORMALMENTE", categoria: "ENTREGUE", alerta: false },
    "2": { descricao: "ENTREGA FORA DA DATA PROGRAMADA", categoria: "ATRASO", alerta: true },
    "3": { descricao: "RECUSA POR FALTA DE PEDIDO DE COMPRA", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "4": { descricao: "RECUSA POR PEDIDO DE COMPRA CANCELADO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "5": { descricao: "FALTA DE ESPACO FISICO NO DEPOSITO DO CLIENTE DE DESTINO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "6": { descricao: "ENDERECO DO CLIENTE DESTINO NAO FOI LOCALIZADO.", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "7": { descricao: "DEVOLUCAO NAO AUTORIZADA PELO CLIENTE", categoria: "DEVOLUCAO", alerta: true },
    "8": { descricao: "PRECO DA MERCADORIA EM DESACORDO COM O PEDIDO DE COMPRA", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "9": { descricao: "MERCADORIA EM DESACORDO COM O PEDIDO DE COMPRA", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "10": { descricao: "CLIENTE DESTINO SOMENTE RECEBE MERCADORIA COM FRETE PAGO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "11": { descricao: "RECUSA POR DEFICIENCIA EMBALAGEM MERCADORIA", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "12": { descricao: "REDESPACHO NAO INDICADO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "13": { descricao: "TRANSPORTADORA NAO ATENDE A CIDADE DO CLIENTE DESTINO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "14": { descricao: "MERCADORIA SINISTRADA", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "15": { descricao: "EMBALAGEM SINISTRADA", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "16": { descricao: "PEDIDO DE COMPRAS EM DUPLICIDADE", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "17": { descricao: "MERCADORIA FORA DA EMBALAGEM DE ATACADISTA", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "18": { descricao: "MERCADORIAS TROCADAS", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "19": { descricao: "REENTREGA SOLICITADA PELO CLIENTE.", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "20": { descricao: "ENTREGA PREJUDICADA POR HORARIO/FALTA DE TEMPO HABIL", categoria: "ATRASO", alerta: true },
    "21": { descricao: "ESTABELECIMENTO FECHADO.", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "22": { descricao: "REENTREGA SEM COBRANCA DO CLIENTE", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "23": { descricao: "EXTRAVIO DE MERCADORIA EM TRANSITO", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "24": { descricao: "MERCADORIA REENTREGUE AO CLIENTE DESTINO", categoria: "ENTREGUE", alerta: false },
    "25": { descricao: "ENVIO DEVOLVIDO AO CLIENTE DE ORIGEM", categoria: "DEVOLUCAO", alerta: true },
    "26": { descricao: "NOTA FISCAL RETIDA PELA FISCALIZACAO", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "27": { descricao: "ROUBO DE CARGA", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "28": { descricao: "MERCADORIA RETIDA ATE SEGUNDA ORDEM", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "29": { descricao: "CLIENTE RETIRA MERCADORIA NA TRANSPORTADORA", categoria: "AGUARDANDO RETIRADA", alerta: false },
    "30": { descricao: "PROBLEMA COM A DOCUMENTACAO (NOTA FISCAL / CTRC)", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "31": { descricao: "ENTREGA COM INDENIZACAO EFETUADA", categoria: "INDENIZACAO", alerta: true },
    "32": { descricao: "FALTA COM SOLICITACAO DE REPOSICAO", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "33": { descricao: "FALTA COM BUSCA/RECONFERENCIA", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "34": { descricao: "CLIENTE FECHADO PARA BALANCO.", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "35": { descricao: "QUANTIDADE DE PRODUTO EM DESACORDO (NOTA FISCAL E/OU PEDIDO)", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "36": { descricao: "BAIXA POR SINISTRO", categoria: "INDENIZACAO", alerta: true },
    "37": { descricao: "BAIXA FISCAL", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "38": { descricao: "BAIXA SEM COMPROVANTE (DO AGENTE)", categoria: "OUTROS / INTERNO", alerta: false },
    "41": { descricao: "PEDIDO DE COMPRA INCOMPLETO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "42": { descricao: "NOTA FISCAL COM PRODUTOS DE SETORES DIFERENTES", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "43": { descricao: "FERIADO LOCAL/NACIONAL", categoria: "ATRASO", alerta: true },
    "44": { descricao: "EXCESSO DE VEICULOS", categoria: "ATRASO", alerta: true },
    "45": { descricao: "CLIENTE DESTINO ENCERROU ATIVIDADES", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "46": { descricao: "RESPONSAVEL DE RECEBIMENTO AUSENTE", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "47": { descricao: "CLIENTE DESTINO EM GREVE", categoria: "ATRASO", alerta: true },
    "48": { descricao: "AEROPORTO FECHADO NO DESTINO", categoria: "ATRASO", alerta: true },
    "49": { descricao: "VOO CANCELADO", categoria: "ATRASO", alerta: false },
    "50": { descricao: "GREVE NACIONAL (GREVE GERAL)", categoria: "ATRASO", alerta: true },
    "51": { descricao: "MERCADORIA VENCIDA (DATA DE VALIDADE EXPIRADA)", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "52": { descricao: "MERCADORIA REDESPACHADA (ENTREGUE PARA REDESPACHO)", categoria: "EM TRANSITO", alerta: false },
    "55": { descricao: "LOCAL DE ENTREGA COM RESTRIÇÃO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "60": { descricao: "ENDEREÇO DE ENTREGA ERRADO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "65": { descricao: "ENTRAR EM CONTATO COM O COMPRADOR", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "66": { descricao: "TROCA NAO DISPONIVEL", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "67": { descricao: "FINS ESTATISTICOS", categoria: "OUTROS / INTERNO", alerta: false },
    "68": { descricao: "DATA DE ENTREGA DIFERENTE DO PEDIDO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "69": { descricao: "SUBSTITUICAO TRIBUTARIA", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "70": { descricao: "SISTEMA FORA DO AR.", categoria: "OUTROS / INTERNO", alerta: false },
    "71": { descricao: "CLIENTE DESTINO NAO RECEBE PEDIDO PARCIAL", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "72": { descricao: "CLIENTE DESTINO SO RECEBE PEDIDO PARCIAL", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "73": { descricao: "REDESPACHO SOMENTE COM FRETE PAGO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "74": { descricao: "FUNCIONARIO NAO AUTORIZADO A RECEBER MERCADORIAS", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "75": { descricao: "MERCADORIA EMBARCADA PARA ROTA INDEVIDA", categoria: "ATRASO", alerta: true },
    "76": { descricao: "ESTRADA/ENTRADA DE ACESSO INTERDITADA", categoria: "ATRASO", alerta: true },
    "77": { descricao: "CLIENTE DESTINO MUDOU DE ENDERECO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "78": { descricao: "AVARIA TOTAL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "79": { descricao: "AVARIA PARCIAL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "80": { descricao: "EXTRAVIO TOTAL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "81": { descricao: "EXTRAVIO PARCIAL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "82": { descricao: "SOBRA DE MERCADORIA SEM NOTA FISCAL", categoria: "OUTROS / INTERNO", alerta: false },
    "83": { descricao: "MERCADORIA EM PODER DA SUFRAMA PARA INTERNACAO", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "84": { descricao: "MERCADORIA RETIRADA PARA CONFERENCIA", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "85": { descricao: "APREENSAO FISCAL DA MERCADORIA", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "86": { descricao: "EXCESSO DE CARGA/PESO", categoria: "ATRASO", alerta: true },
    "87": { descricao: "DESTINATÁRIO EM FÉRIAS COLETIVAS", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "88": { descricao: "RECUSA AGUARDANDO NEGOCIAÇÃO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "91": { descricao: "ENTREGA PROGRAMADA.", categoria: "EM TRANSITO", alerta: false },
    "92": { descricao: "PROBLEMAS FISCAIS", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "93": { descricao: "FALTA PARCIAL DE CARGA.", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "94": { descricao: "FALTA TOTAL DE CARGA.", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "95": { descricao: "FALTA DO CONHECIMENTO.", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "96": { descricao: "FALTA DE NOTA FISCAL.", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "97": { descricao: "RECOLHIMENTO DA CARGA O SETOR DE PROCESSOS", categoria: "OUTROS / INTERNO", alerta: false },
    "98": { descricao: "RO ENVIADA A WINE", categoria: "OUTROS / INTERNO", alerta: false },
    "99": { descricao: "OUTROS TIPOS DE OCORRENCIAS NAO ESPECIFICADOS ACIMA", categoria: "OCORRENCIA NAO ESPECIFICADA", alerta: true },
    "100": { descricao: "EMISSAO DO CONHECIMENTO DE TRANSPORTE.", categoria: "EM TRANSITO", alerta: false },
    "101": { descricao: "ALTERACAO DO CONHECIMENTO DE TRANSPORTE.", categoria: "EM TRANSITO", alerta: false },
    "102": { descricao: "IMPRESSAO DO CONHECIMENTO DE TRANSPORTE", categoria: "EM TRANSITO", alerta: false },
    "103": { descricao: "IMPRESSAO DAS ETIQUETAS DO CONHECIMENTO.", categoria: "EM TRANSITO", alerta: false },
    "104": { descricao: "EMISSAO DE MANIFESTO DE SAIDA.", categoria: "EM TRANSITO", alerta: false },
    "105": { descricao: "ENTRADA DO MANIFESTO NA UNIDADE.", categoria: "EM TRANSITO", alerta: false },
    "106": { descricao: "EMISSAO DA LISTAGEM DE ENTREGAS.", categoria: "EM TRANSITO", alerta: false },
    "107": { descricao: "CANCELAMENTO DO CONHECIMENTO.", categoria: "CANCELAMENTO", alerta: true },
    "108": { descricao: "REIMPRESSAO DE CONHECIMENTO.", categoria: "EM TRANSITO", alerta: false },
    "109": { descricao: "COD FECHOU E NAO DEU BAIXA DE ENTREGA", categoria: "OUTROS / INTERNO", alerta: false },
    "110": { descricao: "COD FOI VENDIDO E NAO DEU BAIXA DE ENTREGA", categoria: "OUTROS / INTERNO", alerta: false },
    "111": { descricao: "UNIDADE REATIVADA", categoria: "OUTROS / INTERNO", alerta: false },
    "112": { descricao: "CARGA RECEBIDA EM VOO FORA DA ROTERIZAÇÃO", categoria: "ATRASO", alerta: true },
    "113": { descricao: "RETORNO DE EDI COM CONHECIMENTOS EMITIDOS.", categoria: "EM TRANSITO", alerta: false },
    "114": { descricao: "RETORNO DE EDI COM OCORRENCIAS DE ENTREGA.", categoria: "EM TRANSITO", alerta: false },
    "115": { descricao: "RETORNO DE EDI COM FATURAS PROCESSADAS.", categoria: "EM TRANSITO", alerta: false },
    "116": { descricao: "BAIXA DA LISTAGEM DE ENTREGAS.", categoria: "EM TRANSITO", alerta: false },
    "117": { descricao: "REMOCAO DO AWB DA LISTAGEM DE ENTREGAS.", categoria: "EM TRANSITO", alerta: false },
    "118": { descricao: "BAIXA FORCADA PELO SISTEMA", categoria: "OUTROS / INTERNO", alerta: false },
    "119": { descricao: "ALTERACAO NA MODALIDADE DE PAGAMENTO", categoria: "EM TRANSITO", alerta: false },
    "120": { descricao: "AGUARDANDO RETORNO DO COMPROVANTE DE ENTREGA.", categoria: "EM TRANSITO", alerta: false },
    "121": { descricao: "IMPRESSAO DA ETIQUETA DO ENVELOPE DE COMPROVANTES.", categoria: "EM TRANSITO", alerta: false },
    "122": { descricao: "EMISSAO DA RELACAO DE ENVELOPES DE COMPROVANTES.", categoria: "EM TRANSITO", alerta: false },
    "123": { descricao: "ENTRADA DA RELACAO DE ENVELOPES DE COMPROVANTES.", categoria: "EM TRANSITO", alerta: false },
    "124": { descricao: "BAIXA DA RELACAO DE ENVELOPES DE COMPROVANTES.", categoria: "EM TRANSITO", alerta: false },
    "125": { descricao: "ENTREGA DO COMPROVANTE PARA O CLIENTE.", categoria: "EM TRANSITO", alerta: false },
    "126": { descricao: "TRANSFERENCIA DE UNIDADE FORCADA.", categoria: "EM TRANSITO", alerta: false },
    "127": { descricao: "UNITIZACAO DA CARGA.", categoria: "EM TRANSITO", alerta: false },
    "128": { descricao: "DESUNITIZACAO DA CARGA", categoria: "EM TRANSITO", alerta: false },
    "129": { descricao: "CONHECIMENTO NAO RECEBIDO PELA DESUNITIZACAO DA CARGA.", categoria: "EM TRANSITO", alerta: false },
    "130": { descricao: "CARGA LOCALIZADA INTEGRALMENTE", categoria: "EM TRANSITO", alerta: false },
    "131": { descricao: "CARGA LOCALIZADA PARCIALMENTE", categoria: "EM TRANSITO", alerta: false },
    "132": { descricao: "MUDANCA DE OFF-LOAD", categoria: "REMANEJAMENTO DE VOO", alerta: false },
    "133": { descricao: "SAIDA DO VEICULO", categoria: "EM TRANSITO", alerta: false },
    "134": { descricao: "SAIDA DO VOO", categoria: "EM TRANSITO", alerta: false },
    "135": { descricao: "EMBARQUE DE CARGA EM ULD", categoria: "EM TRANSITO", alerta: false },
    "136": { descricao: "CHEGADA DO VEICULO", categoria: "EM TRANSITO", alerta: false },
    "137": { descricao: "CHEGADA DO VOO", categoria: "EM TRANSITO", alerta: false },
    "138": { descricao: "EMBARQUE DE CARGA NO VOO", categoria: "EM TRANSITO", alerta: false },
    "139": { descricao: "ABRIR VEICULO PARA CONFERENCIA", categoria: "EM TRANSITO", alerta: false },
    "142": { descricao: "CARREGAMENTO DO VEICULO", categoria: "EM TRANSITO", alerta: false },
    "143": { descricao: "RECEBER E POSIOCIONAR PARA TRIAGEM", categoria: "EM TRANSITO", alerta: false },
    "144": { descricao: "EM PROCESSO DE CONFERENCIA", categoria: "EM TRANSITO", alerta: false },
    "145": { descricao: "O USUARIO ALTEROU O AWB ANTES DA IMPRESSAO", categoria: "EM TRANSITO", alerta: false },
    "146": { descricao: "O USUARIO REIMPRIMIU O MANIFESTO DE CARGAS", categoria: "EM TRANSITO", alerta: false },
    "150": { descricao: "EMISSAO AWB PRIMITIVO", categoria: "EM TRANSITO", alerta: false },
    "160": { descricao: "EM ANALISE PARA CANCELAMENTO.", categoria: "CANCELAMENTO", alerta: true },
    "170": { descricao: "CANCELAMENTO RECUSADO.", categoria: "CANCELAMENTO", alerta: true },
    "171": { descricao: "FECHAMENTO DA LISTAGEM DE CARGA DO VEICULO", categoria: "EM TRANSITO", alerta: false },
    "172": { descricao: "SAIDA AUTORIZADA DO VEICULO DE ENTREGA", categoria: "EM TRANSITO", alerta: false },
    "173": { descricao: "CANCELAMENTO DA LISTAGEM DE CARGA DO VEICULO", categoria: "CANCELAMENTO", alerta: true },
    "180": { descricao: "CARGA EXTRAVIADA - EM PROCESSO DE BUSCA", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "181": { descricao: "CARGA AVARIADA - EM PROCESSO DE APURACAO", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "182": { descricao: "CARGA VIOLADA - EM PROCESSO DE APURACAO", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "183": { descricao: "CARGA ROUBADA - EM PROCESSO DE APURACAO", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "184": { descricao: "ATRASO NA ENTREGA - EM PROCESSO DE APURACAO", categoria: "ATRASO", alerta: true },
    "185": { descricao: "PROCESSO DE INDENIZACAO INICIADO PELA BASE", categoria: "INDENIZACAO", alerta: true },
    "186": { descricao: "PROCESSO DE INDENIZACAO CANCELADO", categoria: "INDENIZACAO", alerta: true },
    "187": { descricao: "PROCESSO DE INDENIZACAO EM ANALISE", categoria: "INDENIZACAO", alerta: true },
    "188": { descricao: "PROCESSO DE INDENIZACAO ENCAMINHADO PARA PAGAMENTO", categoria: "INDENIZACAO", alerta: true },
    "189": { descricao: "PROCESSO DE INDENIZACAO ENCAMINHADO PARA SEGURADO", categoria: "INDENIZACAO", alerta: true },
    "190": { descricao: "INDENIZACAO PAGA AO CLIENTE", categoria: "INDENIZACAO", alerta: true },
    "191": { descricao: "INDENIZACAO JULGADA IMPROCEDENTE", categoria: "INDENIZACAO", alerta: true },
    "192": { descricao: "INDENIZACAO SUSPENSA - CARGA LOCALIZADA", categoria: "INDENIZACAO", alerta: true },
    "200": { descricao: "POSICIONAMENTO DE CARGA EM LOCATION", categoria: "EM TRANSITO", alerta: false },
    "201": { descricao: "CONEXAO IMEDIATA DE VOO.", categoria: "EM TRANSITO", alerta: false },
    "202": { descricao: "STOCK", categoria: "EM TRANSITO", alerta: false },
    "203": { descricao: "ALLOCATED", categoria: "EM TRANSITO", alerta: false },
    "204": { descricao: "LOAD", categoria: "EM TRANSITO", alerta: false },
    "205": { descricao: "INFLIGHT", categoria: "EM TRANSITO", alerta: false },
    "206": { descricao: "UNLOAD", categoria: "EM TRANSITO", alerta: false },
    "207": { descricao: "MAINTENANCE/LOAN", categoria: "EM TRANSITO", alerta: false },
    "208": { descricao: "OUT OF SERVICE", categoria: "EM TRANSITO", alerta: false },
    "209": { descricao: "SCRAP", categoria: "EM TRANSITO", alerta: false },
    "210": { descricao: "LOST/STOLEN", categoria: "EM TRANSITO", alerta: false },
    "211": { descricao: "ULD DISABLED", categoria: "EM TRANSITO", alerta: false },
    "212": { descricao: "ULD RE-ENABLED", categoria: "EM TRANSITO", alerta: false },
    "250": { descricao: "CORTE DE CARGA DO VEICULO", categoria: "REMANEJAMENTO DE VOO", alerta: false },
    "251": { descricao: "RETIRADA DE CARGA DO VEICULO", categoria: "REMANEJAMENTO DE VOO", alerta: false },
    "252": { descricao: "CORTE DE CARGA DO VOO", categoria: "REMANEJAMENTO DE VOO", alerta: false },
    "253": { descricao: "RETIRADA DE CARGA DO VOO", categoria: "REMANEJAMENTO DE VOO", alerta: false },
    "254": { descricao: "RETIRADA DE CARGA DA ULD", categoria: "EM TRANSITO", alerta: false },
    "255": { descricao: "DESEMBARQUE DE CARGA DA ULD", categoria: "EM TRANSITO", alerta: false },
    "256": { descricao: "ULD LACRADA", categoria: "EM TRANSITO", alerta: false },
    "257": { descricao: "ULD DESLACRADA", categoria: "EM TRANSITO", alerta: false },
    "301": { descricao: "EMISSAO DE MANIFESTO PARA ANALISE DE FATURAMETO", categoria: "EM TRANSITO", alerta: false },
    "302": { descricao: "ALTERACAO DE CONHECIMENTO REJEITADO EMITIDO EM FSDA.", categoria: "OUTROS / INTERNO", alerta: false },
    "303": { descricao: "EMISSAO DE CT-E COM EPEC. EVENTO REGISTRADO.", categoria: "EM TRANSITO", alerta: false },
    "304": { descricao: "EMISSAO DE CT-E COM EPEC. USO AUTORIZADO.", categoria: "EM TRANSITO", alerta: false },
    "350": { descricao: "BAIXA DE CONHECIMENTO DESFEITA", categoria: "OUTROS / INTERNO", alerta: false },
    "375": { descricao: "ALTERACAO DE CT-E.", categoria: "EM TRANSITO", alerta: false },
    "376": { descricao: "ALTERACAO DE COURIER.", categoria: "EM TRANSITO", alerta: false },
    "400": { descricao: "DANO/AVARIA PERMISSÍVEL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "401": { descricao: "DANO/AVARIA NÃO PERMISSÍVEL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "402": { descricao: "ULD ENVIADO PARA REPARO", categoria: "OUTROS / INTERNO", alerta: false },
    "403": { descricao: "ULD REPARADO", categoria: "OUTROS / INTERNO", alerta: false },
    "404": { descricao: "MISSING ULD", categoria: "OUTROS / INTERNO", alerta: false },
    "405": { descricao: "INVENTARIO", categoria: "OUTROS / INTERNO", alerta: false },
    "406": { descricao: "OUTRAS OCORRENCIAS", categoria: "OUTROS / INTERNO", alerta: false },
    "425": { descricao: "COTACAO INCLUIDA.", categoria: "EM TRANSITO", alerta: false },
    "426": { descricao: "COTACAO EDITADA.", categoria: "EM TRANSITO", alerta: false },
    "450": { descricao: "COLETA INCLUIDA.", categoria: "COLETA / REVERSA", alerta: false },
    "451": { descricao: "COLETA SINISTRADA.", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "452": { descricao: "COLETA RECUSADA.", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "453": { descricao: "COLETA EM ANDAMENTO.", categoria: "COLETA / REVERSA", alerta: false },
    "454": { descricao: "COLETA CANCELADA", categoria: "CANCELAMENTO", alerta: true },
    "455": { descricao: "COLETA SOLICITADA", categoria: "COLETA / REVERSA", alerta: false },
    "456": { descricao: "COLETA ALTERADA", categoria: "COLETA / REVERSA", alerta: false },
    "457": { descricao: "COLETA ACEITA", categoria: "COLETA / REVERSA", alerta: false },
    "458": { descricao: "COLETA PENDENTE", categoria: "COLETA / REVERSA", alerta: false },
    "459": { descricao: "COLETA REALIZADA", categoria: "COLETA / REVERSA", alerta: false },
    "460": { descricao: "MINUTA INCLUIDA", categoria: "EM TRANSITO", alerta: false },
    "461": { descricao: "MINUTA EDITADA", categoria: "EM TRANSITO", alerta: false },
    "462": { descricao: "MINUTA UTILIZADA NA EMISSAO", categoria: "EM TRANSITO", alerta: false },
    "500": { descricao: "PRODUTO NAO ENTRA NA RESIDENCIA", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "501": { descricao: "COLETA PRODUTO MONTADO", categoria: "COLETA / REVERSA", alerta: false },
    "502": { descricao: "COLETA TROCA CASADA", categoria: "COLETA / REVERSA", alerta: false },
    "503": { descricao: "REVERSA - COLETADO", categoria: "COLETA / REVERSA", alerta: false },
    "504": { descricao: "REVERSA - NOTA DE COLETA EXTRAVIADA", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "505": { descricao: "AUSENTE 1º TENTATIVA", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "506": { descricao: "AUSENTE 2º TENTATIVA", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "507": { descricao: "AUSENTE 3º TENTATIVA", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "508": { descricao: "LOJA RECUSOU PROCESSO DE COLETA", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "509": { descricao: "LOJA FECHADA", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "510": { descricao: "DADOS INSUFICIENTES PARA ENTREGA", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "511": { descricao: "DESTINATARIO DESCONHECIDO NO LOCAL", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "512": { descricao: "RECUSADO POR TERCEIRO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "513": { descricao: "EXCESSO DE CHUVA", categoria: "ATRASO", alerta: true },
    "514": { descricao: "DIFICULDADES NA REGIAO DE ENTREGA", categoria: "ATRASO", alerta: true },
    "515": { descricao: "LOJA FECHADA ENTREGA", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "516": { descricao: "DIFICULDADES NA REGIÃO DE COLETA", categoria: "ATRASO", alerta: true },
    "517": { descricao: "PASSAGEM PELA FISCALIZACAO", categoria: "FISCAL LIBERADO / ADUANA", alerta: false },
    "518": { descricao: "PEDIDO RECUSADO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "519": { descricao: "RECUSA POR FALTA DE AGENDAMENTO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "520": { descricao: "FALTA DE ESPAÇO FÍSICO NO DESTINATÁRIO", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "521": { descricao: "PREÇO DA MERCADORIA EM DESACORDO COM O PEDIDO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "522": { descricao: "AGUARDANDO AGENDAMENTO", categoria: "ATRASO", alerta: true },
    "523": { descricao: "ACIDENTE", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "524": { descricao: "EXTRAVIO DE DOCUMENTOS", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "525": { descricao: "NOTA FISCAL LIBERADA DA FISCALIZAÇÃO", categoria: "FISCAL LIBERADO / ADUANA", alerta: false },
    "526": { descricao: "VOO CANCELADO", categoria: "ATRASO", alerta: true },
    "527": { descricao: "AGUARDANDO RETIRADA DO OBJETO", categoria: "AGUARDANDO RETIRADA", alerta: false },
    "528": { descricao: "CONTATO COM O CLIENTE", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "529": { descricao: "TROCA DE OFF LOAD", categoria: "REMANEJAMENTO DE VOO", alerta: false },
    "531": { descricao: "ATENDIMENTO CALL CENTER (EXCLUSIVO CALL CENTER)", categoria: "OUTROS / INTERNO", alerta: false },
    "532": { descricao: "OCORRENCIA WINE (USO EXCLUSIVO SOL)", categoria: "OUTROS / INTERNO", alerta: false },
    "533": { descricao: "ENCAMINHADO PARA SEFAZ", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "534": { descricao: "LIBERADO PELA SEFAZ", categoria: "FISCAL LIBERADO / ADUANA", alerta: false },
    "535": { descricao: "WINE FINALIZAÇÃO PROCESSO INDENIZATÓRIO", categoria: "INDENIZACAO", alerta: true },
    "536": { descricao: "EM PROCESSO DE LIBERAÇÃO SUFRAMA", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "537": { descricao: "CLIENTE DESCONHECIDO NO LOCAL", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "538": { descricao: "CARGA RECEBIDA PARCIAL NO PA", categoria: "ATRASO", alerta: true },
    "539": { descricao: "CARGA NAO RECEBIDA NO PA", categoria: "ATRASO", alerta: true },
    "540": { descricao: "CARGA RETIDA PARA VERIFICAÇÃO", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "600": { descricao: "INDENIZAÇÃO PAGA EM 16/01/2019", categoria: "INDENIZACAO", alerta: true },
    "601": { descricao: "CT-E CANCELADO POR REJEICAO.", categoria: "CANCELAMENTO", alerta: true },
    "602": { descricao: "PROBLEMAS COM VEÍCULO (QUEBRA/ACIDENTE/RASTREADOR)", categoria: "ATRASO", alerta: true },
    "603": { descricao: "CHEGADA ANTECIPADA DEVIDO REQUERIMENTO COMERCIAL SAMSUNG", categoria: "OUTROS / INTERNO", alerta: false },
    "604": { descricao: "CHEGADA ANTECIPADA DEVIDO A REQUERIMENTO DO CLIENTE", categoria: "OUTROS / INTERNO", alerta: false },
    "605": { descricao: "FALTA DO DOCUMENTO XML", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "606": { descricao: "AGENDAMENTO PARCIAL DO SHIPMENT/MANIFESTO", categoria: "ATRASO", alerta: true },
    "607": { descricao: "AGENDAMENTO FORA DO DIA FIXO", categoria: "ATRASO", alerta: true },
    "608": { descricao: "DIVERGÊNCIA DE BOOKING", categoria: "OUTROS / INTERNO", alerta: false },
    "609": { descricao: "DIFERENTES PRODUTOS NO MESMO CAMINHÃO", categoria: "OUTROS / INTERNO", alerta: false },
    "610": { descricao: "FALTA DE VEÍCULO", categoria: "ATRASO", alerta: true },
    "611": { descricao: "EMBARCADA PARA DESTINO INCORRETO", categoria: "ATRASO", alerta: true },
    "612": { descricao: "DIFERENTES CLIENTES NO MESMO CAMINHÃO", categoria: "OUTROS / INTERNO", alerta: false },
    "613": { descricao: "ERRO IOD (REVERTIDO)", categoria: "OUTROS / INTERNO", alerta: false },
    "614": { descricao: "FALHA NO PLANEJAMENTO", categoria: "ATRASO", alerta: true },
    "615": { descricao: "PERDA DE DOCUMENTAÇÃO (NF /CTE)", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "616": { descricao: "ERRO IOD (SEM REVERSÃO)", categoria: "OUTROS / INTERNO", alerta: false },
    "617": { descricao: "RECUSA POR FALTA DE PAGAMENTO DE DESCARGA", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "618": { descricao: "ATRASO DE COLETA", categoria: "ATRASO", alerta: true },
    "619": { descricao: "ATRASO NO TRANSIT TIME", categoria: "ATRASO", alerta: true },
    "620": { descricao: "AVARIA DE EMBALAGEM", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "621": { descricao: "ENTREGA FORA DO PADRÃO DO CLIENTE", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "622": { descricao: "FALTA COM BUSCA/RECONFERÊNCIA", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "623": { descricao: "FALTA COM BUSCA/RECONFERÊNCIA", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "624": { descricao: "MERCADORIAS TROCADAS (FÍSICO DIFERENTE DA NF) NA TRANSPORTAD", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "625": { descricao: "PROBLEMA COM A DOCUMENTAÇÃO (CTRC/NF/PIN)", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "626": { descricao: "ATRASO TRANSIT TIME 1° LEG", categoria: "ATRASO", alerta: true },
    "627": { descricao: "DIVERGÊNCIA NA CRIAÇÃO DE SM (SOLICITAÇÃO DE MONITORAMENTO)", categoria: "OUTROS / INTERNO", alerta: false },
    "628": { descricao: "CARGA DISPONÍVEL PARA ENTREGA", categoria: "AGUARDANDO RETIRADA", alerta: false },
    "629": { descricao: "DAMAGE (CLAIM)", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "630": { descricao: "VALIDAÇÃO DE NOTA FISCAL", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "631": { descricao: "INSPEÇÃO DE PRODUTO (TESTE)", categoria: "OUTROS / INTERNO", alerta: false },
    "632": { descricao: "DIVERGÊNCIA NO PORTAL DO CLIENTE (AGENDA/PEDIDO /VALORES)", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "633": { descricao: "MÃO DE OBRA SOLICITADA PARA DESCARGA", categoria: "OUTROS / INTERNO", alerta: false },
    "634": { descricao: "RETIDO NA SEFAZ - PAGAMENTO DE ICMS", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "635": { descricao: "DIVERGENCIA DE FATURAMENTO (IMPOSTO, MODELO, PEDIDO)", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "636": { descricao: "DIVERGENCIA ENTRE ACTUAL IOD E POD", categoria: "OUTROS / INTERNO", alerta: false },
    "637": { descricao: "DEMORA NA DESCARGA (APOS FREE TIME)", categoria: "OUTROS / INTERNO", alerta: false },
    "638": { descricao: "AGENDAMENTO CANCELADO/ALTERADO PELO CLIENTE", categoria: "ATRASO", alerta: true },
    "639": { descricao: "DIVERGÊNCIA INTERNA DE RECEBIMENTO DO CLIENTE", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "640": { descricao: "FALTA DE ESPAÇO FÍSICO NO ARMAZÉM DO CLIENTE", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "641": { descricao: "COMPROVANTE DE ENTREGA RETIDO PARA CONFERENCIA DA CARGA", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "642": { descricao: "CLIENTE AUSENTE", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "643": { descricao: "ACIMA DA CAPACIDADE AÉREA", categoria: "ATRASO", alerta: true },
    "644": { descricao: "DIVERGÊNCIA DE IMPOSTOS (FATURAMENTO)", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "645": { descricao: "DIVERGÊNCIA NO CADASTRO DO CLIENTE (CNPJ/EAN/ENDEREÇO)", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "646": { descricao: "DIVERGENCIA NO PEDIDO DE COMPRA (PRECO/QUANTIDADE/MODELO)", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "647": { descricao: "BLOQUEIO FINANCEIRO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "648": { descricao: "POD ESCANEADO VALIDADO RECEBIDO DA TRANSPORTADORA", categoria: "OUTROS / INTERNO", alerta: false },
    "649": { descricao: "INSPEÇÃO DE QUALIDADE", categoria: "OUTROS / INTERNO", alerta: false },
    "650": { descricao: "FALTA DE ACESSÓRIOS", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "651": { descricao: "NOTA FISCAL RETIDA PELA FISCALIZACAO (CONFERÊNCIA) POR CAUSA", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "652": { descricao: "RETIDO - SUFRAMA", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "653": { descricao: "ESTRADA BLOQUEADOS / ENTRADA / ACESSO FECHADO", categoria: "ATRASO", alerta: true },
    "654": { descricao: "GREVE EM ÓRGÃOS DO GOVERNO", categoria: "ATRASO", alerta: true },
    "655": { descricao: "NOTA FISCAL RETIDA PELA FISCALIZACAO (CONFERÊNCIA)", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "656": { descricao: "CAUSAS NATURAIS", categoria: "ATRASO", alerta: true },
    "657": { descricao: "OTIMIZAÇÃO DE AGENDA", categoria: "ATRASO", alerta: true },
    "658": { descricao: "DIVERGÊNCIA DE PROGRAMAÇÃO", categoria: "ATRASO", alerta: true },
    "659": { descricao: "AVARIA DE CONTAINER", categoria: "OUTROS / INTERNO", alerta: false },
    "660": { descricao: "INSPEÇÃO DE CONTAINER", categoria: "OUTROS / INTERNO", alerta: false },
    "661": { descricao: "PROBLEMA SISTÊMICO", categoria: "OCORRENCIA NAO ESPECIFICADA", alerta: true },
    "662": { descricao: "FALTA DE ESCOLTA", categoria: "OCORRENCIA NAO ESPECIFICADA", alerta: true },
    "663": { descricao: "ATRASO DE ESCOLTA", categoria: "OCORRENCIA NAO ESPECIFICADA", alerta: true },
    "664": { descricao: "PROBLEMA LIBERAÇÃO BAÚ/VEÍCULO (SISTEMA)", categoria: "OCORRENCIA NAO ESPECIFICADA", alerta: true },
    "665": { descricao: "ERRO DE SISTEMA (SAP/ OU TSS)", categoria: "OUTROS / INTERNO", alerta: false },
    "666": { descricao: "AVARIA DE EMBALAGEM TOTAL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "667": { descricao: "AVARIA DE EMBALAGEM PARCIAL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "668": { descricao: "CODIGO EAN INCORRETO", categoria: "OUTROS / INTERNO", alerta: false },
    "669": { descricao: "RECUSA POR PRODUTO FORA DO PADRÃO DE PALETIZAÇÃO", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "700": { descricao: "ATRASO NA EXPEDICAO", categoria: "ATRASO", alerta: true },
    "777": { descricao: "CORRECAO ICMS", categoria: "OUTROS / INTERNO", alerta: false },
    "800": { descricao: "EM TRAMITE ADUANEIRO NA ORIGEM", categoria: "FISCAL LIBERADO / ADUANA", alerta: false },
    "801": { descricao: "LIBERADA - AGUARDANDO VOO INTERNACIONAL", categoria: "FISCAL LIBERADO / ADUANA", alerta: false },
    "802": { descricao: "EM TRAMITE ADUANEIRO NO DESTINO", categoria: "FISCAL LIBERADO / ADUANA", alerta: false },
    "803": { descricao: "LIBERADA - TRANSFERENCIA DOMESTICA", categoria: "FISCAL LIBERADO / ADUANA", alerta: false },
    "804": { descricao: "EM ROTA PARA ENTREGA", categoria: "EM TRANSITO", alerta: false },
    "805": { descricao: "DOCUMENTAÇÃO INCORRETA/INCOMPLETA", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "806": { descricao: "RETIDA PELA ADUANA LOCAL", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "807": { descricao: "INADIMITIDA PELA ADUANA LOCAL", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "808": { descricao: "EM PROCESSO DE DEVOLUÇÃO MERCADO LIVRE", categoria: "DEVOLUCAO", alerta: true },
    "809": { descricao: "PACOTE PERDIDO PELO PARCEIRO INTL", categoria: "AVARIA / EXTRAVIO / ROUBO", alerta: true },
    "998": { descricao: "BAIXA POR DUPLICIDADE EDI", categoria: "OUTROS / INTERNO", alerta: false },
    "999": { descricao: "REMARK DA CARGA", categoria: "OUTROS / INTERNO", alerta: false },
    "1000": { descricao: "DEVOLUÇÃO SOLICITADA PELO CLIENTE - FRAUDE", categoria: "DEVOLUCAO", alerta: true },
    "1010": { descricao: "BAIXA REALIZADA CONFORMA INVENTARIO", categoria: "OUTROS / INTERNO", alerta: false },
    "1108": { descricao: "REIMPRESSAO DE ETIQUETAS", categoria: "EM TRANSITO", alerta: false },
    "1109": { descricao: "ENTREGA BLOQUEADA PELO REMETENTE", categoria: "TENTATIVA DE ENTREGA FALHOU", alerta: true },
    "2626": { descricao: "NOTA FISCAL RETIDA PELA FISCALIZACAO MERCADO LIVRE", categoria: "RETIDO FISCAL / DOCUMENTACAO", alerta: true },
    "7001": { descricao: "MERCADORIAS TROCADAS (FÍSICO DIFERENTE DA NF) NO ARMAZÉM", categoria: "RECUSA PELO DESTINATARIO", alerta: true },
    "BKD": { descricao: "BOOKED (RESERVA CRIADA)", categoria: "EM TRANSITO", alerta: false },
    "ATM": { descricao: "ADDED TO MANIFEST (INCLUIDO NO MANIFESTO)", categoria: "EM TRANSITO", alerta: false },
    "UPDATE": { descricao: "ATUALIZACAO / REIMPRESSAO DE ETIQUETA", categoria: "EM TRANSITO", alerta: false },
    "PLN": { descricao: "ASSIGNED TO CART (SEPARADO PARA CARREGAMENTO)", categoria: "EM TRANSITO", alerta: false },
    "END TRIP": { descricao: "END TRIP (FIM DA ROTA DE ENTREGA)", categoria: "EM TRANSITO", alerta: false },
};

module.exports = { CODIGOS_AZUL };
