// Portado de correios-rastreio-crm (ESM compilado) para CommonJS; lógica idêntica. Rastreio SRO Rastro dos Correios.
const CODIGOS_CORREIOS = {
    "BDE|00": { descricao: "Objeto entregue ao destinatário", categoria: "ENTREGUE", alerta: false, acao: "Finalizar - rastro concluído" },
    "BDE|01": { descricao: "Objeto entregue ao destinatário", categoria: "ENTREGUE", alerta: false, acao: "Finalizar - rastro concluído" },
    "BDI|00": { descricao: "Objeto entregue ao destinatário", categoria: "ENTREGUE", alerta: false, acao: "Finalizar - rastro concluído" },
    "BDI|01": { descricao: "Objeto entregue ao destinatário", categoria: "ENTREGUE", alerta: false, acao: "Finalizar - rastro concluído" },
    "BDR|00": { descricao: "Objeto entregue ao destinatário", categoria: "ENTREGUE", alerta: false, acao: "Finalizar - rastro concluído" },
    "BDR|01": { descricao: "Objeto entregue ao destinatário", categoria: "ENTREGUE", alerta: false, acao: "Finalizar - rastro concluído" },
    "BDE|02": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (aguardar retirada na unidade)", categoria: "AGUARDANDO_RETIRADA", alerta: true, acao: "Avisar cliente para retirar na agência" },
    "BDI|02": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (aguardar retirada na unidade)", categoria: "AGUARDANDO_RETIRADA", alerta: true, acao: "Avisar cliente para retirar na agência" },
    "BDR|02": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (aguardar retirada na unidade)", categoria: "AGUARDANDO_RETIRADA", alerta: true, acao: "Avisar cliente para retirar na agência" },
    "BDE|03": { descricao: "Remetente não retirou objeto na Unidade dos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Retirar o objeto devolvido na agência" },
    "BDI|03": { descricao: "Remetente não retirou objeto na Unidade dos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Retirar o objeto devolvido na agência" },
    "BDR|03": { descricao: "Remetente não retirou objeto na Unidade dos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Retirar o objeto devolvido na agência" },
    "BDE|04": { descricao: "A entrega não pode ser efetuada - Cliente recusou-se a receber", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDI|04": { descricao: "A entrega não pode ser efetuada - Cliente recusou-se a receber", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDR|04": { descricao: "A entrega não pode ser efetuada - Cliente recusou-se a receber", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDE|05": { descricao: "A entrega não pode ser efetuada", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDI|05": { descricao: "A entrega não pode ser efetuada", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDR|05": { descricao: "A entrega não pode ser efetuada", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDE|06": { descricao: "A entrega não pode ser efetuada - Cliente desconhecido no local", categoria: "DEVOLUCAO", alerta: true, acao: "Confirmar endereço/destinatário com o cliente" },
    "BDI|06": { descricao: "A entrega não pode ser efetuada - Cliente desconhecido no local", categoria: "DEVOLUCAO", alerta: true, acao: "Confirmar endereço/destinatário com o cliente" },
    "BDR|06": { descricao: "A entrega não pode ser efetuada - Cliente desconhecido no local", categoria: "DEVOLUCAO", alerta: true, acao: "Confirmar endereço/destinatário com o cliente" },
    "BDE|07": { descricao: "A entrega não pode ser efetuada - Endereço incorreto (sujeito a atraso ou devolução)", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDI|07": { descricao: "A entrega não pode ser efetuada - Endereço incorreto (sujeito a atraso ou devolução)", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDR|07": { descricao: "A entrega não pode ser efetuada - Endereço incorreto (sujeito a atraso ou devolução)", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDE|08": { descricao: "A entrega não pode ser efetuada - Endereço incorreto (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Corrigir endereço e reenviar" },
    "BDI|08": { descricao: "A entrega não pode ser efetuada - Endereço incorreto (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Corrigir endereço e reenviar" },
    "BDR|08": { descricao: "A entrega não pode ser efetuada - Endereço incorreto (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Corrigir endereço e reenviar" },
    "BDE|09": { descricao: "Objeto não localizado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDI|09": { descricao: "Objeto não localizado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDR|09": { descricao: "Objeto não localizado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDE|10": { descricao: "A entrega não pode ser efetuada - Cliente mudou-se", categoria: "DEVOLUCAO", alerta: true, acao: "Obter novo endereço com o cliente" },
    "BDI|10": { descricao: "A entrega não pode ser efetuada - Cliente mudou-se", categoria: "DEVOLUCAO", alerta: true, acao: "Obter novo endereço com o cliente" },
    "BDR|10": { descricao: "A entrega não pode ser efetuada - Cliente mudou-se", categoria: "DEVOLUCAO", alerta: true, acao: "Obter novo endereço com o cliente" },
    "BDE|12": { descricao: "Remetente não retirou objeto na Unidade dos Correios (análise de destinação)", categoria: "DEVOLUCAO", alerta: true, acao: "Acionar atendimento dos Correios" },
    "BDI|12": { descricao: "Remetente não retirou objeto na Unidade dos Correios (análise de destinação)", categoria: "DEVOLUCAO", alerta: true, acao: "Acionar atendimento dos Correios" },
    "BDR|12": { descricao: "Remetente não retirou objeto na Unidade dos Correios (análise de destinação)", categoria: "DEVOLUCAO", alerta: true, acao: "Acionar atendimento dos Correios" },
    "BDE|19": { descricao: "A entrega não pode ser efetuada - Endereço incorreto", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDI|19": { descricao: "A entrega não pode ser efetuada - Endereço incorreto", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDR|19": { descricao: "A entrega não pode ser efetuada - Endereço incorreto", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDE|20": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (nova tentativa)", categoria: "TENTATIVA", alerta: true, acao: "Avisar cliente sobre nova tentativa" },
    "BDI|20": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (nova tentativa)", categoria: "TENTATIVA", alerta: true, acao: "Avisar cliente sobre nova tentativa" },
    "BDR|20": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (nova tentativa)", categoria: "TENTATIVA", alerta: true, acao: "Avisar cliente sobre nova tentativa" },
    "BDE|21": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDI|21": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDR|21": { descricao: "A entrega não pode ser efetuada - Carteiro não atendido (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDE|22": { descricao: "Objeto devolvido aos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar" },
    "BDI|22": { descricao: "Objeto devolvido aos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar" },
    "BDR|22": { descricao: "Objeto devolvido aos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar" },
    "BDE|23": { descricao: "Objeto devolvido ao remetente", categoria: "DEVOLUCAO", alerta: true, acao: "Receber devolução e tratar pedido" },
    "BDI|23": { descricao: "Objeto devolvido ao remetente", categoria: "DEVOLUCAO", alerta: true, acao: "Receber devolução e tratar pedido" },
    "BDR|23": { descricao: "Objeto devolvido ao remetente", categoria: "DEVOLUCAO", alerta: true, acao: "Receber devolução e tratar pedido" },
    "BDE|24": { descricao: "Objeto disponível para retirada em Caixa Postal", categoria: "AGUARDANDO_RETIRADA", alerta: false, acao: "Acompanhar" },
    "BDI|24": { descricao: "Objeto disponível para retirada em Caixa Postal", categoria: "AGUARDANDO_RETIRADA", alerta: false, acao: "Acompanhar" },
    "BDR|24": { descricao: "Objeto disponível para retirada em Caixa Postal", categoria: "AGUARDANDO_RETIRADA", alerta: false, acao: "Acompanhar" },
    "BDE|25": { descricao: "A entrega não pode ser efetuada (entrega no próximo dia útil)", categoria: "TENTATIVA", alerta: false, acao: "Acompanhar" },
    "BDE|26": { descricao: "Destinatário não retirou objeto na Unidade dos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDI|26": { descricao: "Destinatário não retirou objeto na Unidade dos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDR|26": { descricao: "Destinatário não retirou objeto na Unidade dos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDE|28": { descricao: "Objeto e/ou conteúdo avariado", categoria: "AVARIA", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDI|28": { descricao: "Objeto e/ou conteúdo avariado", categoria: "AVARIA", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDR|28": { descricao: "Objeto e/ou conteúdo avariado", categoria: "AVARIA", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDE|32": { descricao: "Objeto com data de entrega agendada", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDI|32": { descricao: "Objeto com data de entrega agendada", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDR|32": { descricao: "Objeto com data de entrega agendada", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDE|33": { descricao: "A entrega não pode ser efetuada - Destinatário não apresentou documento exigido", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDI|33": { descricao: "A entrega não pode ser efetuada - Destinatário não apresentou documento exigido", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDR|33": { descricao: "A entrega não pode ser efetuada - Destinatário não apresentou documento exigido", categoria: "DEVOLUCAO", alerta: true, acao: "Contatar cliente" },
    "BDE|34": { descricao: "A entrega não pode ser efetuada - Logradouro com numeração irregular", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDI|34": { descricao: "A entrega não pode ser efetuada - Logradouro com numeração irregular", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDR|34": { descricao: "A entrega não pode ser efetuada - Logradouro com numeração irregular", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "BDE|35": { descricao: "Coleta ou entrega de objeto não efetuada (nova tentativa)", categoria: "TENTATIVA", alerta: true, acao: "Avisar cliente sobre nova tentativa" },
    "BDI|35": { descricao: "Coleta ou entrega de objeto não efetuada (nova tentativa)", categoria: "TENTATIVA", alerta: true, acao: "Avisar cliente sobre nova tentativa" },
    "BDR|35": { descricao: "Coleta ou entrega de objeto não efetuada (nova tentativa)", categoria: "TENTATIVA", alerta: true, acao: "Avisar cliente sobre nova tentativa" },
    "BDE|36": { descricao: "Coleta ou entrega de objeto não efetuada (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDI|36": { descricao: "Coleta ou entrega de objeto não efetuada (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDR|36": { descricao: "Coleta ou entrega de objeto não efetuada (será devolvido)", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDE|37": { descricao: "Objeto e/ou conteúdo avariado por acidente com veículo", categoria: "AVARIA", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDI|37": { descricao: "Objeto e/ou conteúdo avariado por acidente com veículo", categoria: "AVARIA", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDR|37": { descricao: "Objeto e/ou conteúdo avariado por acidente com veículo", categoria: "AVARIA", alerta: true, acao: "Abrir manifestação nos Correios" },
    "BDE|38": { descricao: "Objeto endereçado à empresa falida", categoria: "DEVOLUCAO", alerta: true, acao: "Verificar com o cliente" },
    "BDI|38": { descricao: "Objeto endereçado à empresa falida", categoria: "DEVOLUCAO", alerta: true, acao: "Verificar com o cliente" },
    "BDR|38": { descricao: "Objeto endereçado à empresa falida", categoria: "DEVOLUCAO", alerta: true, acao: "Verificar com o cliente" },
    "BDE|40": { descricao: "A importação do objeto/conteúdo não foi autorizada pelos órgãos fiscalizadores", categoria: "FISCAL", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDI|40": { descricao: "A importação do objeto/conteúdo não foi autorizada pelos órgãos fiscalizadores", categoria: "FISCAL", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDR|40": { descricao: "A importação do objeto/conteúdo não foi autorizada pelos órgãos fiscalizadores", categoria: "FISCAL", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDE|41": { descricao: "A entrega do objeto está condicionada à composição do lote", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDI|41": { descricao: "A entrega do objeto está condicionada à composição do lote", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDR|41": { descricao: "A entrega do objeto está condicionada à composição do lote", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDE|42": { descricao: "Lote de objetos incompleto", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDI|42": { descricao: "Lote de objetos incompleto", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDR|42": { descricao: "Lote de objetos incompleto", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDE|43": { descricao: "Objeto apreendido por órgão de fiscalização ou outro órgão anuente", categoria: "FISCAL", alerta: true, acao: "Acionar atendimento dos Correios" },
    "BDI|43": { descricao: "Objeto apreendido por órgão de fiscalização ou outro órgão anuente", categoria: "FISCAL", alerta: true, acao: "Acionar atendimento dos Correios" },
    "BDR|43": { descricao: "Objeto apreendido por órgão de fiscalização ou outro órgão anuente", categoria: "FISCAL", alerta: true, acao: "Acionar atendimento dos Correios" },
    "BDE|45": { descricao: "Objeto recebido na unidade de distribuição", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "BDI|45": { descricao: "Objeto recebido na unidade de distribuição", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "BDR|45": { descricao: "Objeto recebido na unidade de distribuição", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "BDE|46": { descricao: "Tentativa de entrega não efetuada - Empresa sem expediente", categoria: "TENTATIVA", alerta: false, acao: "Entrega no próximo dia útil" },
    "BDI|46": { descricao: "Tentativa de entrega não efetuada - Empresa sem expediente", categoria: "TENTATIVA", alerta: false, acao: "Entrega no próximo dia útil" },
    "BDR|46": { descricao: "Tentativa de entrega não efetuada - Empresa sem expediente", categoria: "TENTATIVA", alerta: false, acao: "Entrega no próximo dia útil" },
    "BDE|47": { descricao: "Saída para entrega cancelada", categoria: "TENTATIVA", alerta: false, acao: "Acompanhar - novo lançamento para entrega" },
    "BDI|47": { descricao: "Saída para entrega cancelada", categoria: "TENTATIVA", alerta: false, acao: "Acompanhar - novo lançamento para entrega" },
    "BDR|47": { descricao: "Saída para entrega cancelada", categoria: "TENTATIVA", alerta: false, acao: "Acompanhar - novo lançamento para entrega" },
    "BDE|48": { descricao: "Retirada em Unidade dos Correios não autorizada pelo remetente", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDI|48": { descricao: "Retirada em Unidade dos Correios não autorizada pelo remetente", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDR|48": { descricao: "Retirada em Unidade dos Correios não autorizada pelo remetente", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDE|49": { descricao: "As dimensões do objeto impossibilitam o tratamento e a entrega", categoria: "DEVOLUCAO", alerta: true, acao: "Rever embalagem e reenviar" },
    "BDI|49": { descricao: "As dimensões do objeto impossibilitam o tratamento e a entrega", categoria: "DEVOLUCAO", alerta: true, acao: "Rever embalagem e reenviar" },
    "BDR|49": { descricao: "As dimensões do objeto impossibilitam o tratamento e a entrega", categoria: "DEVOLUCAO", alerta: true, acao: "Rever embalagem e reenviar" },
    "BDE|50": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDE|51": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDE|52": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDI|50": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDI|51": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDI|52": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDR|50": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDR|51": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDR|52": { descricao: "Objeto roubado", categoria: "EXTRAVIO", alerta: true, acao: "Abrir manifestação e reenviar ao cliente" },
    "BDE|53": { descricao: "Objeto reimpresso e reenviado", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDI|53": { descricao: "Objeto reimpresso e reenviado", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDR|53": { descricao: "Objeto reimpresso e reenviado", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "BDE|54": { descricao: "Para recebimento do objeto, é necessário o pagamento do ICMS Importação", categoria: "FISCAL", alerta: true, acao: "Acompanhar" },
    "BDI|54": { descricao: "Para recebimento do objeto, é necessário o pagamento do ICMS Importação", categoria: "FISCAL", alerta: true, acao: "Acompanhar" },
    "BDR|54": { descricao: "Para recebimento do objeto, é necessário o pagamento do ICMS Importação", categoria: "FISCAL", alerta: true, acao: "Acompanhar" },
    "BDE|55": { descricao: "Solicitada revisão do tributo estabelecido", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDI|55": { descricao: "Solicitada revisão do tributo estabelecido", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDR|55": { descricao: "Solicitada revisão do tributo estabelecido", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDE|56": { descricao: "Declaração aduaneira ausente ou incorreta", categoria: "FISCAL", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDI|56": { descricao: "Declaração aduaneira ausente ou incorreta", categoria: "FISCAL", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDR|56": { descricao: "Declaração aduaneira ausente ou incorreta", categoria: "FISCAL", alerta: true, acao: "Acompanhar retorno ao remetente" },
    "BDE|57": { descricao: "Revisão de tributo concluída - Objeto liberado", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDI|57": { descricao: "Revisão de tributo concluída - Objeto liberado", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDR|57": { descricao: "Revisão de tributo concluída - Objeto liberado", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDE|58": { descricao: "Revisão de tributo concluída - Tributo alterado", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDI|58": { descricao: "Revisão de tributo concluída - Tributo alterado", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDR|58": { descricao: "Revisão de tributo concluída - Tributo alterado", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDE|59": { descricao: "Revisão de tributo concluída - Tributo mantido", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDI|59": { descricao: "Revisão de tributo concluída - Tributo mantido", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDR|59": { descricao: "Revisão de tributo concluída - Tributo mantido", categoria: "FISCAL", alerta: false, acao: "Acompanhar" },
    "BDE|66": { descricao: "Área com distribuição sujeita a prazo diferenciado (restrição de entrega domiciliar temporária)", categoria: "ATRASO", alerta: false, acao: "Acompanhar" },
    "BDI|66": { descricao: "Área com distribuição sujeita a prazo diferenciado (restrição de entrega domiciliar temporária)", categoria: "ATRASO", alerta: false, acao: "Acompanhar" },
    "BDR|66": { descricao: "Área com distribuição sujeita a prazo diferenciado (restrição de entrega domiciliar temporária)", categoria: "ATRASO", alerta: false, acao: "Acompanhar" },
    "BDE|69": { descricao: "Objeto com atraso na entrega", categoria: "ATRASO", alerta: true, acao: "Avisar cliente sobre o atraso" },
    "BDI|69": { descricao: "Objeto com atraso na entrega", categoria: "ATRASO", alerta: true, acao: "Avisar cliente sobre o atraso" },
    "BDR|69": { descricao: "Objeto com atraso na entrega", categoria: "ATRASO", alerta: true, acao: "Avisar cliente sobre o atraso" },
    "BLQ|01": { descricao: "Entrega de objeto bloqueada a pedido do remetente", categoria: "BLOQUEIO", alerta: true, acao: "Confirmar se o bloqueio foi pedido pela Seu Boné" },
    "CD|00": { descricao: "Objeto recebido na Unidade dos Correios", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "CD|01": { descricao: "Objeto recebido na Unidade dos Correios", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "CD|02": { descricao: "Objeto recebido na Unidade dos Correios", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "CD|03": { descricao: "Objeto recebido na Unidade dos Correios", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "CMT|00": { descricao: "Objeto recebido na Unidade dos Correios", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "CO|01": { descricao: "Objeto coletado", categoria: "POSTAGEM", alerta: false, acao: "Acompanhar" },
    "CUN|00": { descricao: "Objeto recebido na Unidade dos Correios", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "CUN|01": { descricao: "Objeto recebido na Unidade dos Correios", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "DO|00": { descricao: "Objeto encaminhado", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "DO|01": { descricao: "Objeto encaminhado", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "DO|02": { descricao: "Objeto encaminhado", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "EST|01": { descricao: "Favor desconsiderar a informação anterior (estorno)", categoria: "ESTORNO", alerta: false, acao: "Reavaliar o evento anterior" },
    "EST|02": { descricao: "Favor desconsiderar a informação anterior (estorno)", categoria: "ESTORNO", alerta: false, acao: "Reavaliar o evento anterior" },
    "EST|03": { descricao: "Favor desconsiderar a informação anterior (estorno)", categoria: "ESTORNO", alerta: false, acao: "Reavaliar o evento anterior" },
    "EST|04": { descricao: "Favor desconsiderar a informação anterior (estorno)", categoria: "ESTORNO", alerta: false, acao: "Reavaliar o evento anterior" },
    "EST|05": { descricao: "Favor desconsiderar a informação anterior (estorno)", categoria: "ESTORNO", alerta: false, acao: "Reavaliar o evento anterior" },
    "EST|06": { descricao: "Favor desconsiderar a informação anterior (estorno)", categoria: "ESTORNO", alerta: false, acao: "Reavaliar o evento anterior" },
    "EST|09": { descricao: "Favor desconsiderar a informação anterior (estorno)", categoria: "ESTORNO", alerta: false, acao: "Reavaliar o evento anterior" },
    "FC|01": { descricao: "Objeto será devolvido por solicitação do remetente", categoria: "DEVOLUCAO", alerta: true, acao: "Confirmar se a devolução foi pedida pela Seu Boné" },
    "FC|02": { descricao: "Objeto com data de entrega agendada", categoria: "INFO", alerta: false, acao: "Acompanhar" },
    "FC|03": { descricao: "Objeto mal encaminhado", categoria: "ATRASO", alerta: true, acao: "Acompanhar - encaminhamento a ser corrigido" },
    "FC|04": { descricao: "A entrega não pode ser efetuada - Endereço incorreto", categoria: "ENDERECO", alerta: true, acao: "Confirmar endereço com o cliente" },
    "FC|05": { descricao: "Objeto devolvido aos Correios", categoria: "DEVOLUCAO", alerta: true, acao: "Acompanhar" },
    "FC|07": { descricao: "A entrega não pode ser efetuada - Empresa sem expediente", categoria: "TENTATIVA", alerta: false, acao: "Entrega no próximo dia útil" },
    "IDC|01": { descricao: "Objeto não localizado - houve indenização", categoria: "EXTRAVIO", alerta: true, acao: "Reenviar ao cliente e conferir indenização" },
    "IDC|02": { descricao: "Objeto não localizado - houve indenização", categoria: "EXTRAVIO", alerta: true, acao: "Reenviar ao cliente e conferir indenização" },
    "IDC|03": { descricao: "Objeto não localizado - houve indenização", categoria: "EXTRAVIO", alerta: true, acao: "Reenviar ao cliente e conferir indenização" },
    "IDC|04": { descricao: "Objeto não localizado - houve indenização", categoria: "EXTRAVIO", alerta: true, acao: "Reenviar ao cliente e conferir indenização" },
    "IDC|05": { descricao: "Objeto não localizado - houve indenização", categoria: "EXTRAVIO", alerta: true, acao: "Reenviar ao cliente e conferir indenização" },
    "IDC|06": { descricao: "Objeto não localizado - houve indenização", categoria: "EXTRAVIO", alerta: true, acao: "Reenviar ao cliente e conferir indenização" },
    "IDC|07": { descricao: "Objeto não localizado - houve indenização", categoria: "EXTRAVIO", alerta: true, acao: "Reenviar ao cliente e conferir indenização" },
    "LDE|09": { descricao: "Objeto saiu para entrega ao remetente", categoria: "DEVOLUCAO", alerta: true, acao: "Preparar recebimento da devolução" },
    "LDI|00": { descricao: "Objeto aguardando retirada no endereço indicado", categoria: "AGUARDANDO_RETIRADA", alerta: true, acao: "Avisar cliente para retirar" },
    "LDI|01": { descricao: "Objeto aguardando retirada no endereço indicado", categoria: "AGUARDANDO_RETIRADA", alerta: true, acao: "Avisar cliente para retirar" },
    "LDI|03": { descricao: "Objeto aguardando retirada no endereço indicado", categoria: "AGUARDANDO_RETIRADA", alerta: true, acao: "Avisar cliente para retirar" },
    "LDI|14": { descricao: "Objeto aguardando retirada no endereço indicado", categoria: "AGUARDANDO_RETIRADA", alerta: true, acao: "Avisar cliente para retirar" },
    "LDI|02": { descricao: "Objeto disponível para retirada em Caixa Postal", categoria: "AGUARDANDO_RETIRADA", alerta: false, acao: "Acompanhar" },
    "OEC|00": { descricao: "Objeto saiu para entrega ao destinatário", categoria: "SAIU_ENTREGA", alerta: false, acao: "Acompanhar" },
    "OEC|01": { descricao: "Objeto saiu para entrega ao destinatário", categoria: "SAIU_ENTREGA", alerta: false, acao: "Acompanhar" },
    "PAR|15": { descricao: "Objeto em unidade internacional/alfândega", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "PAR|16": { descricao: "Objeto em unidade internacional/alfândega", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "PAR|17": { descricao: "Objeto em unidade internacional/alfândega", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "PAR|18": { descricao: "Objeto em unidade internacional/alfândega", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "PMT|01": { descricao: "Objeto encaminhado", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "PO|00": { descricao: "Objeto postado", categoria: "POSTAGEM", alerta: false, acao: "Acompanhar" },
    "PO|01": { descricao: "Objeto postado", categoria: "POSTAGEM", alerta: false, acao: "Acompanhar" },
    "PO|09": { descricao: "Objeto postado após o horário limite da unidade", categoria: "POSTAGEM", alerta: false, acao: "Encaminhamento no próximo dia útil" },
    "RO|00": { descricao: "Objeto em transferência", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "RO|01": { descricao: "Objeto em transferência", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
    "TRI|00": { descricao: "Objeto encaminhado", categoria: "TRANSITO", alerta: false, acao: "Acompanhar" },
};

module.exports = { CODIGOS_CORREIOS };
